def generate_llm_report(name, age, glucose, bmi, prediction):

    if glucose > 140:
        glucose_text = "elevated glucose levels"
    else:
        glucose_text = "normal glucose levels"

    if bmi > 30:
        bmi_text = "obesity-related risk"
    elif bmi > 25:
        bmi_text = "overweight risk"
    else:
        bmi_text = "healthy body mass"

    report = f"""
AI MEDICAL INTERPRETATION

Patient Name: {name}
Age: {age}

The AI diabetes prediction system indicates: {prediction}.

Clinical Interpretation:
The patient shows {glucose_text} and {bmi_text}. 
These factors can significantly influence diabetes risk.

Lifestyle Recommendations:
• Maintain a balanced low-sugar diet
• Engage in regular physical activity
• Monitor blood glucose periodically
• Maintain healthy body weight

Medical Advice:
Consult a healthcare professional for further diagnostic evaluation 
if symptoms such as frequent urination, excessive thirst, or fatigue occur.

Note:
This report is generated by an AI-assisted decision support system 
and should not replace professional medical advice.
"""

    return report